import React, {Component} from 'react';

class PersonalStatement extends Component {
  render(){
    return(<div>
      <div className='personal'>
        Some type of personal statement....
        Some type of personal statement....
        Some type of personal statement....
        Some type of personal statement....
        Some type of personal statement....
        Some type of personal statement....
        Some type of personal statement....
        Some type of personal statement....
        Some type of personal statement....
        Some type of personal statement....
        Some type of personal statement....
        Some type of personal statement....
        Some type of personal statement....
        Some type of personal statement....
        Some type of personal statement....
        Some type of personal statement....
      </div>
    </div>)
  }
}

export default PersonalStatement;
